import "./globals.css";
import Navbar from "@/components/Navbar/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <div className="max-h-screen min-h-[85vh]">{children}</div>
      </body>
    </html>
  );
}
